language: swift
osx_image: xcode11.3

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

cache:
  - bundler
  - cocoapods

before_install:
  - gem install cocoapods -v '1.8.4'
  - pod install --repo-update
  - brew update
  - brew install swiftlint || true

script:
  - set -o pipefail
  - xcodebuild -workspace AlphaWallet.xcworkspace -scheme AlphaWalletTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X" test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
